name: Artifacts Demo

on: workflow_dispatch

jobs:
    job_1: Upload Artifact
    runs-on: ubuntu-latest

    steps:
        - name: "Create a local file"
          run: echo "Something new happened" > file.txt"

        - uses: actions/upload-artifact@v2

         with: 
             name: file
             path: file.txt
             retention-days: 10


    job_2: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
        - uses: actions/download-artifact@v2
          with:
            name: file
        - name: Printing the fiel content
          run: cat fiel.txt