name: Artifacts Demo

on: workflow_dispatch

jobs:
  job_1:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: "Create a local file"
        run: echo "Running build process" > file.txt

      - uses: actions/upload-artifact@v4

        with:
          name: file
          path: file.txt
          retention-days: 10

  job_2:
    name: Deploy
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: file
      - name: Printing the file content
        run: cat file.txt
