name: "List Default ENV variabls"
on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

jobs:
  ububtu-environment-variabls:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$JAVA_HOME_11_X64"

  windows-environment-variabls:
    runs-on: windows-latest
    steps:
      - run: env

  macos-environment-variabls:
    runs-on: macos-latest
    steps:
      - run: env
